# Powerline style with Nord color palette

format = """
[](nord0)\
$username\
$hostname\
$container\
$os\
[](bg:nord1 fg:nord0)\
$directory\
[](bg:nord2 fg:nord1)\
$git_branch\
$git_status\
$git_metrics\
[](bg:nord3 fg:nord2)\
$c\
$elixir\
$elm\
$golang\
$python\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:nord3)\
$kubernetes
$status
"""
#[](fg:foreground)

scan_timeout = 50
command_timeout = 1000
add_newline = false
palette = 'dracula'

[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
nord0 = '#2E3440'
nord1 = '#3B4252'
nord2 = '#434C5E'
nord3 = '#4C566A'

[palettes.nord]
nord0 = '#2E3440'
nord1 = '#3B4252'
nord2 = '#434C5E'
nord3 = '#4C566A'
nord4 = '#D8DEE9'
nord7 = '#8fbcbb'
nord11 = '#BF616A'
nord13 = '#EBCB8B'
nord14 = '#A2BE8A'

# username, host and OS
[username]
style_root = 'bg:nord0 fg:red'
style_user = 'bg:nord0 fg:foreground'
format = '[$user]($style)'
show_always = true
disabled = false

[hostname]
ssh_only = true
ssh_symbol = ' '
trim_at = '.'
format = '[@$hostname$ssh_symbol]($style)'
style = 'bg:nord0 fg:foreground'
detect_env_vars = ['!CONTAINER_ID']
disabled = false

[container]
format = '[ $name ]($style)'
style = 'bg:nord0 fg:yellow'

[os]
format = '[ $symbol ]($style)'
style = 'bg:nord0 fg:foreground'
disabled = false
# for symbols look at the end of the file

# directory
[directory]
truncation_length = 6
truncate_to_repo = false
format = '[ $path ]($style)[$read_only]($read_only_style)'
style = 'bg:nord1 fg:foreground'
disabled = false
read_only = ' 󰌾 '
read_only_style = 'bg:nord1 fg:red'
truncation_symbol = '…/'

[directory.substitutions]
'Documents' = '󰈙'
'Dokumente' = '󰈙'
'Downloads' = ' '
'Music' = ' '
'Musik' = ' '
'Pictures' = ' '
'Bilder' = ' '
'Projects' = ' '

# git
[git_branch]
symbol = ''
style = 'bg:nord2 fg:foreground'
format = '[ $symbol $branch ]($style)'

[git_status]
style = 'bg:nord2 fg:foreground'
format = '[$all_status$ahead_behind ]($style)'

[git_metrics]
added_style = 'bg:nord2 fg:green'
deleted_style = 'bg:nord2 fg:red'
format = '[+$added ]($added_style)[-$deleted ]($deleted_style)'
disabled = false

# programming
[c]
symbol = ' '
style = 'bg:nord3 fg:foreground'
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = ' '
style = 'bg:nord3 fg:foreground'
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = ' '
style = 'bg:nord3 fg:foreground'
format = '[ $symbol ($version) ]($style)'

[golang]
symbol = ' '
style = 'bg:nord3 fg:foreground'
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ' '
style = 'bg:nord3 fg:foreground'
format = '[ $symbol ($version) (\($virtualenv\)) ]($style)'

[gradle]
style = 'bg:nord3 fg:foreground'
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ' '
style = 'bg:nord3 fg:foreground'
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ' '
style = 'bg:nord3 fg:foreground'
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ' '
style = 'bg:nord3 fg:foreground'
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ''
style = 'bg:nord3 fg:foreground'
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = '󰆥 '
style = 'bg:nord3 fg:foreground'
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ''
style = 'bg:nord3 fg:foreground'
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ' '
style = 'bg:nord3 fg:foreground'
format = '[ $symbol ($version) ]($style)'

# status
[status]
format = '[ $symbol ]($style)'
style = "bold"
symbol = '[](fg:red)'
# success_symbol = '[](fg:nord14)'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
not_executable_symbol = '[🛇](fg:red)'
not_found_symbol = '[󰍉](fg:red)'
sigint_symbol = '[](fg:yellow)'
signal_symbol = '[](fg:red)'
disabled = false

# OS symbols
[os.symbols]
Alpaquita = ' '
Alpine = ' '
Amazon = ' '
Android = ' '
Arch = ' '
Artix = ' '
CentOS = ' '
Debian = ' '
DragonFly = ' '
Emscripten = ' '
EndeavourOS = ' '
Fedora = ' '
FreeBSD = ' '
Garuda = '󰛓 '
Gentoo = ' '
HardenedBSD = '󰞌 '
Illumos = '󰈸 '
Linux = ' '
Mabox = ' '
Macos = ' '
Manjaro = ' '
Mariner = ' '
MidnightBSD = ' '
Mint = ' '
NetBSD = ' '
NixOS = ' '
OpenBSD = '󰈺 '
openSUSE = ' '
OracleLinux = '󰌷 '
Pop = ' '
Raspbian = ' '
Redhat = ' '
RedHatEnterprise = ' '
Redox = '󰀘 '
Solus = '󰠳 '
SUSE = ' '
Ubuntu = ' '
Unknown = ' '
Windows = '󰍲 '

[kubernetes]
format = ' on [⛵$context \($namespace\)](comment) '
# detect_files = ['.k8s']
disabled = false
