# alt_send_esc = true
# background_opacity = 1.0
[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-D"]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[colors]
draw_bold_text_with_bright_colors = true

[general]
live_config_reload = true
import = ["~/.config/alacritty/dracula.toml"]

[cursor]
style = "Beam"
unfocused_hollow = true

[font]
size = 17.0

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MesloLGS Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.bold_italic]
family = "MesloLGS Nerd Font"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

# [mouse]
# hide_when_typing = true

# [mouse.double_click]
# threshold = 300
#
# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[window]
decorations = "Full"
dynamic_padding = false
dynamic_title = true
# startup_mode = "Maximized"
title = "Alacritty"
opacity = 1
blur = false
# padding = { x = 0, y = 0}

[window.class]
general = "Alacritty"
instance = "Alacritty"

#
# [window.position]
# x = 0
# y = 0

[keyboard]

[terminal]

